/* descriptions.js
 *  Author: Isaac Simmons
 *  Date Created: 6-24-2023
 *  Last Revised: 12-13-2024
 *  Description: Descriptions for the mass effect character quiz
*/

const characterDescriptions = {
    tali: "You are Tali'Zorah. You may have a quiet demeanor but you still know how to stand up for yourself. Once you do end up opening up to someone you are extremely loyal and caring and your friends can always count on you. You also have a high intelligence. Problem solving and figuring out how things work gives you joy and you are always interested in learning more.",
    garrus: "You are Garrus. You are a fiercely loyal person. When someone needs you, you're there. You value justice and are always accepting of others, but you also are heavily influenced and can be swayed by people you trust. When it comes to getting things done, you are not afraid to take action and are willing to pursue solutions to problems.",
    javik: "You are Javik. You are fierce and unforgiving. You have very little tolerance for others' mistakes and have strong opinions on what should and shouldn't be. At the same time you are a very dedicated and strong person and are loyal to your friends and colleagues. One of your philosophies is that you have no problem doing whatever it takes.",
    liara: "You are Liara. You are kind and gentle to those around you. Your friends are essential to you, and you always strive to make others that you love happy. You also know how to handle yourself if you find yourself in a tough situation. Hard work is something you enjoy, and you are always looking to improve your efficiency in any form that you can. Finally, you also are a very hopeful person, believing that there is good in most people and that with enough effort, good things can always be achieved. ",
    wrex: "You are Wrex. You like to be practical more than anything else, doing things that work and not overcomplicating things. Friendship for you is built on respect. If you respect someone, you’ll be there for them to offer your loyalty and help. You can be a natural leader at times too, easily assuming that role and leading people to success. People respect you for your strength and can always lean on you in times of need.",
    legion: "You are Legion. Your personality can be a bit rigid to others, but they know they can rely on you due to your fierce loyalty. Being methodical and calculating are what you are all about. You enjoy solving problems and breaking issues down. You have a love for life and strive to achieve peace, but you are also not afraid to fight for a cause (usually from a distance) and do what it takes to accomplish your goals. ",
    miranda: "You are Miranda. You are a perfectionist, always making sure everything is accomplished in the best way possible. You only want the best. You are fierce, smart, and strong and are able to do whatever it takes to accomplish your goals. You do have a vulnerable side but only reserve that for those you trust and respect.  You don’t always express your feelings out loud, but you are loyal to your friends and family that you love.",
    jacob: "You are Jacob. You have a soldier’s loyalty. You fight for a cause and are always willing to volunteer when it comes to something that matters. Your personality can be a bit abrasive to others at times, usually having strong opinions and a willingness to be blunt. You do not always make the best decisions when it comes to friendships and romance. Still though, you are willing to do what it takes to protect those that you care about, and that quality is appreciated by those around you. ",
    mordin: "You are Mordin. You have an eccentric personality and are not afraid to express your personal opinions and thoughts. Many may view you as weird or strange, but that does not deter you. Those closest to you love you for who you are. You are also highly intelligent, able to grasp complex topics easily, and take delight in learning new things. This leads to you also being methodical, you always try to analyze things. You are decisive, able to think under pressure and accomplish the goal at hand, even if it may be an ethical dilemma. Finally, you are also always open to helping others close to you.",
    ashley: "You are Ashley. It takes a lot for you to trust others and you can be very judgemental of others different from you. You are tough and straight forward and don't mind saying what's on your mind. That can come off badly to some, but others enjoy that quality that you have. When it comes to accomplishing things, you tend not to overthink or put much thought into it and rather trust that hard work will get the job done. ",
    kaidan: "You are Kaidan. You are loyal and understanding. Always open to new things, you like to give the benefit of the doubt and try and do what you think would be for the greater good. You are also very smart and like solve problems when you can. Overall, you strive to do the right thing and are willing to stand up for what and who you care about.",
    samara: "You are Samara. A calm and commanding presence is what you bring to those around you. You are usually seen as a good listener due to your stillness and attentiveness. You also have very strong values and a strict code that you follow in life. You aren't afraid to cut off people that don't fit into your lifestyle, and are always working towards achieving your goals.",
    thane: "You are Thane. You are someone who always strives to do something efficiently and precisely. You are also quick witted and versatile. You also are someone who thinks a lot and ponders many things about life. Perhaps you are also spiritual, taking time to slow down and pray or meditate. Overall, you are a loyal, efficient, and calculating person, never abandoning your word and always striving to improve.",
    illusiveMan: "You are the Illusive Man. You are someone who accomplishes things, no matter the cost. You have very little moral qualms about things and believe that to achieve something truly great, sacrifices have to be made. You value privacy, always wanting others to know the least about you as possible. You still have loyalties, and try to treat others that help you achieve your goals right, but once they impair your goals you have no problem removing them from the equation. Your philosophy is to do whatever it takes.",
    zaeed: "You are Zaeed. You are ruthless and practical. You do not have have much to show for ethics, only really doing what it takes to accomplish your goals. Respect is something you command, and something you admire in others. You are a determined person as well, always making sure to get the job done, and get it done right, no matter the cost. ",
    kasumi: "You are Kasumi. You are smart and cunning, always thinking on your feet. You like to keep to yourself for the most part, prefering to do activities alone most of the time. However, you still have a place for others in your life and have the ability to get deeply attached to others. You also very much enjoy messing with them. Overall, you're quiet, reserved, and enjoy your alone time, but you are very loyal and loving to your friends.",
    james: "You are James. You are the typical soldier. You are a strong shoulder for others to lean on, and are fiercely loyal to those you love. You have a straight forward outlook in life, you enjoy the thrills, and seek out those that can have fun and enjoy those thrills with you. You do whatever it takes to accomplish your goals and to protect those close to you",
    grunt: "You are Grunt. You respect strength since you are strong yourself. A guiding principle for you is only the strong thrive. This principle informs your decisions wherever you go, willing to fight for a cause or die trying, you don't believe in backing down. You are also a pretty impatient person, never wanting to wait for anything. Another trait is your unpredictability, never being satisfied with following strict sets of rules and instead choosing to do things in whatever reckless way you see fit.",
    jack: "You are Jack. You have a very strong personality and aren’t afraid to express your opinions. People may judge you for how you choose to express yourself, but that doesn’t deter you. You only care about people who get you for who you are. When you have a cause to fight for, you fight hard and fight no matter the consequences. ",
    joker: "You are Joker, someone who may not take every situation seriously. You are very talkative and enjoy sharing your opinions. You also have a heart of gold, however, and are always there for others when they need you. Above all else, you strive to do the right thing and always try to be accommodating to others even if you might mock them a little bit."

}

export { characterDescriptions };